package.json
reference/webhooks.v1.1.json
scripts/build-webhooks-oas3.1.ts
yarn.lock

[UI-webhooks-3.1](https://idtjira.atlassian.net/browse/UI-webhooks-3.1)

feat: [UI-webhooks-3.1] - add first pass at script and reference

---

models/webhooks/message_received.v1.yaml
package.json
reference/webhooks.v1.1.json
scripts/build-webhooks-oas3.1.ts
yarn.lock

[UI-webhooks-3.1](https://idtjira.atlassian.net/browse/UI-webhooks-3.1)

feat: [UI-webhooks-3.1] - fix for message_received and udpate webhooks oas3.1 generator

---

models/webhooks/call_answered.v1.yaml
models/webhooks/call_blind_transfer.v1.yaml
models/webhooks/call_blocked.v1.yaml
models/webhooks/call_busy.v1.yaml
models/webhooks/call_completed.v1.yaml
models/webhooks/call_consultative_transfer.v1.yaml
models/webhooks/call_forward.v1.yaml
models/webhooks/call_hold.v1.yaml
models/webhooks/call_missed.v1.yaml
models/webhooks/call_park.v1.yaml
models/webhooks/call_pickup.v1.yaml
models/webhooks/call_recorded.v1.yaml
models/webhooks/call_recording_failed.v1.yaml
models/webhooks/call_resume.v1.yaml
models/webhooks/call_rg_queue_completed.v1.yaml
models/webhooks/call_rg_queue_entered.v1.yaml
models/webhooks/call_rg_queue_tier.v1.yaml
models/webhooks/call_ringing.v1.yaml
models/webhooks/call_unpark.v1.yaml
models/webhooks/emergency_call.v1.yaml
models/webhooks/message_received.v1.yaml
models/webhooks/voicemail_missed.v1.yaml
models/webhooks/voicemail_notify.v1.yaml
models/webhooks/voicemail_received.v1.yaml
nodemon.webhooks.json
package.json
reference/webhooks.v1.1.json
reference/webhooks.v1.json
scripts/build-webhooks.ts

[N2PCA-470](https://idtjira.atlassian.net/browse/N2PCA-470)

feat: [N2PCA-470] - udpate scripts and models to show examples from model file

---

models/webhooks/call_answered.v1.yaml
models/webhooks/call_blind_transfer.v1.yaml
models/webhooks/call_blocked.v1.yaml
models/webhooks/call_busy.v1.yaml
models/webhooks/call_completed.v1.yaml
models/webhooks/call_consultative_transfer.v1.yaml
models/webhooks/call_forward.v1.yaml
models/webhooks/call_hold.v1.yaml
models/webhooks/call_missed.v1.yaml
models/webhooks/call_park.v1.yaml
models/webhooks/call_pickup.v1.yaml
models/webhooks/call_recorded.v1.yaml
models/webhooks/call_recording_failed.v1.yaml
models/webhooks/call_resume.v1.yaml
models/webhooks/call_rg_queue_completed.v1.yaml
models/webhooks/call_rg_queue_entered.v1.yaml
models/webhooks/call_rg_queue_tier.v1.yaml
models/webhooks/call_ringing.v1.yaml
models/webhooks/call_unpark.v1.yaml
models/webhooks/emergency_call.v1.yaml
models/webhooks/message_received.v1.yaml
models/webhooks/voicemail_missed.v1.yaml
models/webhooks/voicemail_notify.v1.yaml
models/webhooks/voicemail_received.v1.yaml

[N2PCA-event-values](https://idtjira.atlassian.net/browse/N2PCA-event-values)

fix: [N2PCA-event-values] - reorganize allOf for overwriting with rapi-doc

---

models/webhooks/call_answered.v1.yaml
models/webhooks/call_blind_transfer.v1.yaml
models/webhooks/call_blocked.v1.yaml
models/webhooks/call_busy.v1.yaml
models/webhooks/call_completed.v1.yaml
models/webhooks/call_consultative_transfer.v1.yaml
models/webhooks/call_forward.v1.yaml
models/webhooks/call_hold.v1.yaml
models/webhooks/call_missed.v1.yaml
models/webhooks/call_park.v1.yaml
models/webhooks/call_pickup.v1.yaml
models/webhooks/call_recorded.v1.yaml
models/webhooks/call_recording_failed.v1.yaml
models/webhooks/call_resume.v1.yaml
models/webhooks/call_rg_queue_completed.v1.yaml
models/webhooks/call_rg_queue_entered.v1.yaml
models/webhooks/call_rg_queue_tier.v1.yaml
models/webhooks/call_ringing.v1.yaml
models/webhooks/call_unpark.v1.yaml
models/webhooks/emergency_call.v1.yaml
models/webhooks/message_received.v1.yaml
models/webhooks/voicemail_missed.v1.yaml
models/webhooks/voicemail_notify.v1.yaml
models/webhooks/voicemail_received.v1.yaml
reference/webhooks.v1.json

[N2PCA-more-cleanup](https://idtjira.atlassian.net/browse/N2PCA-more-cleanup)

fix: [N2PCA-more-cleanup] - change event example values to correct types

---

toc.json

[N2PCA-491](https://idtjira.atlassian.net/browse/N2PCA-491)

feat: [N2PCA-491] - update toc.json

---

docs/privacy-policy.md
docs/zapier.md

[N2PCA-480](https://idtjira.atlassian.net/browse/N2PCA-480)

feat: [N2PCA-480] - clean up privacy-policy new lines and add zapier doc

---

toc.json

[N2PCA-480](https://idtjira.atlassian.net/browse/N2PCA-480)

feat: [N2PCA-480] - add zapier to toc.json

---

docs/zapier.md

[N2PCA-480](https://idtjira.atlassian.net/browse/N2PCA-480)

feat: [N2PCA-480] - update and use script from markdown

---

models/webhooks/base/c2c-info.v1.yaml
models/webhooks/call_answered.v1.yaml
models/webhooks/call_completed.v1.yaml
models/webhooks/call_missed.v1.yaml
models/webhooks/call_ringing.v1.yaml
models/webhooks/voicemail_missed.v1.yaml
reference/webhooks.v1.json

[N2PCA-509](https://idtjira.atlassian.net/browse/N2PCA-509)

feat: [N2PCA-509] - add c2c info to appropriate webhooks

---

models/webhooks/call_blocked.v1.yaml
models/webhooks/call_hold.v1.yaml
models/webhooks/call_resume.v1.yaml
models/webhooks/call_rg_queue_completed.v1.yaml
models/webhooks/call_rg_queue_entered.v1.yaml
models/webhooks/call_rg_queue_tier.v1.yaml

[N2PCA-509](https://idtjira.atlassian.net/browse/N2PCA-509)

feat: [N2PCA-509] - add more click2call models and examples

---

reference/webhooks.v1.json

[N2PCA-509](https://idtjira.atlassian.net/browse/N2PCA-509)

feat: [N2PCA-509] - add examples to webhooks

---

package.json
references/apis/examples/auth_token.v1.yaml
references/apis/info.yaml
references/apis/parameters/query.client.id.v1.yaml
references/apis/parameters/query.client.secret.v1.yaml
references/apis/parameters/query.state.v1.yaml
references/apis/parameters/query.type.grant.v1.yaml
references/apis/parameters/query.type.response.v1.yaml
references/apis/parameters/query.uri.redirect.v1.yaml
references/apis/paths/authentication.v1.yaml
references/apis/schemas/auth_token.v1.yaml
references/apis/spec.yaml
references/webhooks/info.yaml
references/webhooks/spec.yaml
scripts/build-spec.ts
specs/apis.v1.json
specs/webhooks.v1.json
tsconfig.json
yarn.lock

[N2PCA-468](https://idtjira.atlassian.net/browse/N2PCA-468)

feat: [N2PCA-468] - add authentication endpoints

---

docs/getting-started.md

[N2PCA-612](https://idtjira.atlassian.net/browse/N2PCA-612)

fix: [N2PCA-612] - fix link in getting-started

---

docs/getting-started.md

[N2PCA-612](https://idtjira.atlassian.net/browse/N2PCA-612)

fix: [N2PCA-612] - fix typo

---

docs/getting-started.md

[N2PCA-614](https://idtjira.atlassian.net/browse/N2PCA-614)

fix: [N2PCA-614] - fix curl request format

---

references/apis/paths/authentication.v1.yaml
references/apis/paths/calls.v1.yaml
references/apis/paths/cdrs.v1.yaml
references/apis/paths/users.v1.yaml
references/apis/paths/webhooks.v1.yaml
references/apis/responses/response.429.v1.yaml
scripts/build-spec.ts
scripts/helpers.ts
specs/apis.v1.json

[N2PCA-614](https://idtjira.atlassian.net/browse/N2PCA-614)

feat: [N2PCA-614] - add known rate limits and update 429 response w examples

---

toc.v1.json
toc.v2.json

[N2PCA-545](https://idtjira.atlassian.net/browse/N2PCA-545)

feat: [N2PCA-545] - add toc files with versioning

---

references/webhooks/webhooks/base/audio.v1.yaml
references/webhooks/webhooks/call_recorded.v1.yaml
references/webhooks/webhooks/voicemail_received.v1.yaml
specs/webhooks.v1.json

[N2PCA-623](https://idtjira.atlassian.net/browse/N2PCA-623)

feat: [N2PCA-623] - add audio_message_url to call_recorded and voicemail_received events

---

docs/developer-portal.md
toc.v1.json
toc.v2.json

[N2PCA-686](https://idtjira.atlassian.net/browse/N2PCA-686)

docs: [N2PCA-686] - add dev portal launch doc

---

docs/developer-portal.md

[N2PCA-686](https://idtjira.atlassian.net/browse/N2PCA-686)

docs: [N2PCA-686] - add what we have done so far section

---

references/apis/paths/authentication.v1.yaml
references/apis/paths/calls.v1.yaml
references/apis/paths/cdrs.v1.yaml
references/apis/paths/users.v1.yaml
references/apis/paths/webhooks.v1.yaml
references/apis/schemas/call.v1.yaml
references/apis/schemas/webhook_call.v1.yaml
references/apis/schemas/webhook_subscription.v1.yaml
specs/apis.v1.json

apis.V1 downgraded to OpenAPI v3.0 +
some warnings in apis.V1 fixed

Downgrade n2p-api-gateway V1 to OpenAPI 3.0

---

.github/workflows/publish.yaml
package.json

[PAR-0](https://idtjira.atlassian.net/browse/PAR-0)

feat: [PAR-0] - run build scripts parallel
